package com.batiCuisine.service;

import com.batiCuisine.model.Projet;
import com.batiCuisine.repository.ProjetRepository;

import java.sql.SQLException;

public class ProjetService {
    private ProjetRepository projetRepository;

    public ProjetService(ProjetRepository projetRepository) {
        this.projetRepository = projetRepository;
    }

    // Create a new project
    public int addProjet(Projet projet) throws SQLException {
        return projetRepository.insertProjet(projet);  // Return the ID generated by the repository
    }
    // Method to retrieve a project by its ID
    public Projet getProjetById(int projetId) throws SQLException {
        Projet projet = projetRepository.findById(projetId);
        if (projet == null) {
            throw new IllegalArgumentException("Aucun projet trouvé avec l'ID: " + projetId);
        }
        return projet;
    }
}
